function zhelp --description "Show zellij worktree workflow help"
    set -l bold (set_color --bold)
    set -l dim (set_color brblack)
    set -l cyan (set_color cyan)
    set -l green (set_color green)
    set -l yellow (set_color yellow)
    set -l red (set_color red)
    set -l reset (set_color normal)

    echo ""
    echo "$bold""Zellij Worktree Workflow""$reset"
    echo "$dim""─────────────────────────────────────────────────────$reset"
    echo ""
    echo "$bold""Sessions""$reset"
    echo "  $cyan""zj$reset        Attach/create local zellij session (dalp)"
    echo "  $cyan""zjr$reset       SSH to daystrom + attach/create zellij session (dalp)"
    echo ""
    echo "$bold""Worktree Lifecycle""$reset"
    echo "  $cyan""ztn$reset $dim""<PRD-xxx>$reset  New worktree from Linear ticket (fetches title, opens Claude with /execute)"
    echo "  $cyan""ztnx$reset $dim""<PRD-xxx>$reset New worktree from Linear ticket (opens Codex instead)"
    echo "  $cyan""ztc$reset $dim""<branch>$reset   New worktree from branch name"
    echo "  $cyan""ztg$reset $dim""[PR#]$reset      Checkout a PR as worktree (fzf picker if no # given)"
    echo "  $cyan""ztr$reset              Remove current worktree + close tab (back to main)"
    echo "  $cyan""ztd$reset              Delete a worktree via fzf picker"
    echo ""
    echo "$bold""Navigation & Layout""$reset"
    echo "  $cyan""ztl$reset       List worktrees, cd to selection + open tab"
    echo "  $cyan""zts$reset       Repair current tab layout (lazygit + terminal + Claude)"
    echo "  $cyan""zto$reset       Open orchestrator tab in main DALP repo"
    echo ""
    echo "$bold""Tab Layout""$reset  $dim""(created by ztn/ztc/ztg/ztl/zts)$reset"
    echo "  ┌──────────────────────┬────────────┐"
    echo "  │                      │            │"
    echo "  │   $green""Main (Claude)$reset       │  $yellow""lazygit$reset   │"
    echo "  │        80%           │    30%     │"
    echo "  ├──────────────────────┤            │"
    echo "  │   $dim""Terminal$reset  20%      │            │"
    echo "  └──────────────────────┴────────────┘"
    echo ""
    echo "$dim""─────────────────────────────────────────────────────$reset"
    echo "$bold""Flow 1: Remote dev (daystrom)""$reset"
    echo ""
    echo "  $green""1.$reset zjr                    $dim""# SSH + zellij on daystrom$reset"
    echo "  $green""2.$reset ztn PRD-1234            $dim""# new worktree from ticket$reset"
    echo "     $dim""... or ztc feature/foo  # new worktree from branch$reset"
    echo "     $dim""... or ztg              # checkout a PR$reset"
    echo "  $green""3.$reset $dim""(work in the tab — Claude + lazygit + terminal)$reset"
    echo "  $green""4.$reset ztr                    $dim""# done — remove worktree, close tab$reset"
    echo ""
    echo "$bold""Flow 2: Local dev""$reset"
    echo ""
    echo "  $green""1.$reset zj                     $dim""# start local zellij session$reset"
    echo "  $green""2.$reset ztn PRD-1234            $dim""# same commands as remote$reset"
    echo "  $green""3.$reset $dim""(work in the tab)$reset"
    echo "  $green""4.$reset ztr                    $dim""# done$reset"
    echo ""
    echo "$dim""─────────────────────────────────────────────────────$reset"
    echo "$bold""Dependencies""$reset"
    echo "  zellij, git, gh, fzf, lazygit, linear, wt (worktrunk), claude"
    echo ""
end
